---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: vala-lint
        name: vala-lint
        description: This hook runs vala-lint.
        entry: io.elementary.vala-lint -c .vala-lint.ini
        language: system
        files: \.vala$
